# Generated by Django 5.1.3 on 2024-12-07 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0015_inmueble_estado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inmueble",
            name="distancia",
            field=models.CharField(
                choices=[
                    ("0-5 km", "0-5 km"),
                    ("5-10 km", "5-10 km"),
                    ("10-15 km", "10-15 km"),
                    ("15-20 km", "15-20 km"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="inmueble",
            name="numero_contacto",
            field=models.CharField(max_length=10),
        ),
    ]
