# Generated by Django 5.1.3 on 2024-12-07 00:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0016_alter_inmueble_distancia_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inmueble",
            name="numero_contacto",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z]+$", "El campo solo puede contener letras."
                    )
                ],
                verbose_name="Número de contacto",
            ),
        ),
    ]
