# Generated by Django 5.1.3 on 2024-12-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0017_alter_inmueble_numero_contacto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inmueble",
            name="numero_contacto",
            field=models.CharField(max_length=15),
        ),
    ]
