# Generated by Django 5.1.3 on 2024-12-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0019_alter_inmueble_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inmueble",
            name="numero_contacto",
            field=models.CharField(max_length=10),
        ),
    ]
