# Generated by Django 5.1.3 on 2024-12-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0020_alter_inmueble_numero_contacto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inmueble",
            name="codigo_postal",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="inmueble",
            name="direccion",
            field=models.CharField(max_length=200),
        ),
    ]
