# Generated by Django 5.1.3 on 2024-12-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0021_alter_inmueble_codigo_postal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inmueble",
            name="descripcion",
            field=models.TextField(max_length=500),
        ),
    ]
