# Generated by Django 5.1.3 on 2024-12-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0023_alter_inmueble_precio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inmueble",
            name="precio",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
